version: "3.7"
services:
    postgres:
        container_name: {{ cookiecutter.project_slug }}_postgres_container
        image: postgres:{{ cookiecutter.postgres_version }}
        working_dir: /app
        restart: always
        ports:
            - "{{ cookiecutter.postgres_port }}:5432"
        environment:
            POSTGRES_USER: {{ cookiecutter.postgres_user }}
            POSTGRES_PASSWORD: {{ cookiecutter.postgres_password }}
            POSTGRES_DB: {{ cookiecutter.postgres_dbname }}
        volumes:
            - "./postgres:/var/lib/postgresql"

    {%- if cookiecutter.use_pgadmin == "y" %}

    pgadmin:
        container_name: {{ cookiecutter.project_slug }}_pgadmin_container
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: {{ cookiecutter.pgadmin_email }}
            PGADMIN_DEFAULT_PASSWORD: {{ cookiecutter.pgadmin_password }}
        volumes:
            - "./pgadmin:/var/lib/pgadmin"
        ports:
            - "{{ cookiecutter.pgadmin_port }}:80"
        restart: always
{%- endif %}